# This is a basic copy/paste of version release info from one repo to another

name: Copy Release Details

on:
  repository_dispatch:
    types: [new-release]

jobs:
  copy_release_details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          repository: GenesysGo/docs-shadow-cloud
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Copy release details
        run: |
          version=${{ github.event.client_payload.tag_name }}
          raw_date="${{ github.event.client_payload.published_at }}"
          date=$(date -u -d "$raw_date" +"%B %d, %Y")
          description=$(echo "${{ github.event.client_payload.body }}" | sed ':a;N;$!ba;s/\n/\\n/g')
          release_url="https://github.com/GenesysGo/shadow-drive/releases/tag/$version"
          insert_line=$(grep -n "## Consolidated Summary" reference/change-logs.md | cut -d: -f1)
          insert_line=$((insert_line + 1))
          awk -v n="$insert_line" -v s="\n[$version - $date]($release_url)\n$description\n" 'NR == n {print s} {print}' reference/change-logs.md > reference/change-logs.md.tmp && mv reference/change-logs.md.tmp reference/change-logs.md
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "Your Name"
          author_email: "you@example.com"
          message: "Update change-logs"
          add: "reference/change-logs.md"
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
